export { default as Main } from './Main';
export { default as Login } from './Login';
export { default as Profile } from './Profile';
export { default as MappingHistory } from './MappingHistory';
export { default as MappingResult } from './MappingResult';
export { default as TeamProfile } from './TeamProfile';
export { default as Dashboard } from './Dashboard';
export { default as CodeSystem } from './CodeSystem';
export { default as Register } from './Register';
