version: "2"
volumes:
  onto:
    driver: local
  pgdata:
    driver: local
  mongodb-data:
    name: mongodb-data

networks:
  di-network:
    name: di

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=boxjelly
      - MONGO_INITDB_ROOT_PASSWORD=di_boxjelly90082
    ports:
      - "27017:27017"
    networks:
      - di-network

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ~/data/nginx/logs:/var/log/nginx
      - ~/data/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/data/nginx/ssl:/etc/nginx/ssl
      - ~/data/nginx/html:/usr/share/nginx/html
    networks:
      - di-network

  di-gateway:
    build:
      context: ./src/di-gateway
      dockerfile: Dockerfile
    image: di-gateway
    container_name: di-gateway
    networks:
      - di-network

  di-auth:
    build: 
      context: ./src/di-auth
      dockerfile: Dockerfile
    image: di-auth
    container_name: di-auth
    volumes:
      - ~/data/di-data/di-auth:/data/di-data/di-auth
    networks:
      - di-network

  di-center:
    build: 
      context: ./src/di-center
      dockerfile: Dockerfile
    image: di-center
    container_name: di-center
    networks:
      - di-network

  di-map:
    build: 
      context: ./src/di-map
      dockerfile: Dockerfile
    image: di-map
    container_name: di-map
    volumes:
      - ~/data/di-data/di-map/medcat_model:/data/di-data/di-map/medcat_model
    networks:
      - di-network

  db:
    image: postgres
    container_name: ontoserver-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - di-network

  ontoserver:
    image: quay.io/aehrc/ontoserver:ctsa-6.12.3
    container_name: ontoserver
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - authentication.oauth.endpoint.client_id.0=6i0p6pu3a05mv0rsuq0hds45mm
      - authentication.oauth.endpoint.client_secret.0=1cnbh5btj2h40d0lp0uupnkn1pi0j1uemcl0nm32mgpf9akfiipu
      - JAVA_OPTS=-Xmx4G
    volumes:
      - onto:/var/onto
    networks:
      - di-network