  - name: Update apt cache
    apt:
      update_cache: yes
    become: true
  
  - name: Ensure destination directory exists
    ansible.builtin.file:
      path: '{{work_dir}}'
      state: directory

  # transfer the target module to the remote instance
  - name: Synchronize '{{di_gateway_module_name}}' module code with remote server
    ansible.builtin.synchronize:
      src: '{{local_work_dir}}'
      dest: '{{work_dir}}'
      delete: yes
      recursive: yes
      rsync_opts:
        - "--exclude=.git"
        - "--exclude-from=../.gitignore"