export const UNIVERSAL_INDICATION_LIST = [
  {
    group: 'Bone and Joint',
    children: [
      'Compound or open fracture',
      'Infected prosthetic joint or bone prosthesis',
      'Osteomyelitis',
      "Reactive arthritis (Reiter's disease)",
      'Septic arthritis',
      'Septic bursitis',
      'Infective tenosynovitis',
      'Vertebral osteomyelitis',
      'Septic arthritis: Neisseria gonorrhoeae',
      'Prophylaxis for open fracture',
    ],
  },
  {
    group: 'Cardiovascular system',
    children: [
      'Endocarditis, native valve, pathogen unknown',
      'Endocarditis, prosthetic valve, pathogen unknown',
      'Infected (mycotic) aneurysm',
      'Vascular graft infection',
      'Endocarditis: Staphylococcus aureus',
      'Endocarditis: Enterococcus species',
      'Endocarditis: Streptococcus species',
      'Endocarditis: Coxiella burnetii',
      'Endocarditis; other pathogen(s)',
      'Myocarditis',
      'Pericarditis',
      'Critical limb ischaemia',
      'Endocarditis: Abiotrophia species',
      'Endocarditis: Granulicatella species',
      'Endocarditis: Bartonella spp.',
      'Endovascular device infection',
      'Implantable cardiac device: pocket infection',
      'Implantable cardiac device: lead infection',
      'Left ventricular assist device infection',
      'Endocarditis: Haemophilus species',
      'Endocarditis: Aggregatibacter species',
      'Endocarditis: Cardiobacterium species',
      'Endocarditis: Eikenella corrodens',
      'Endocarditis: Kingella species',
    ],
  },
  {
    group: 'Central Nervous System',
    children: [
      'Bacterial meningitis, community acquired, pathogen unknown',
      'Bacterial meningitis / ventriculitis, healthcare associated, pathogen unknown',
      'Bacterial meningitis: Neisseria meningitidis',
      'Bacterial meningitis: Streptococcus pneumoniae',
      'Bacterial meningitis: Haemophilus influenzae type b',
      'Bacterial meningitis: Listeria monocytogenes',
      'Bacterial meningitis: Group B Streptococcus',
      'Bacterial meningitis: Streptococcus suis',
      'Bacterial meningitis: Escherichia coli',
      'Bacterial meningitis; other pathogen(s)',
      'Subdural empyema',
      'Brain abscess',
      'Cryptococcal meningitis / central nervous system infection',
      'Fungal central nervous system infection',
      'Encephalitis',
      'Primary amoebic encephalitis',
      'Eosinophilic meningitis',
      'Free-living amoeba infection',
      'Epidural abscess',
      'Infected prosthetic neurological device e.g. CSF shunt',
      'Neurocysticercosis',
      'Nocardia, central nervous system',
      'Recurrent benign lymphocytic meningitis',
      'Cerebral Toxoplasmosis',
      'Herpes simplex virus encephalitis',
      'Tuberculosis meningitis',
      'Aseptic meningitis',
      'Viral meningitis',
      'Septic cerebral venous thrombosis',
      'Myelitis',
      'Creutzfeldt-Jakob disease',
      'Cerebral vasculitis, varicella zoster virus',
    ],
  },
  {
    group: 'Ear nose and throat',
    children: [
      'Acute otitis externa, diffuse',
      'Acute epiglottitis',
      'Acute otitis externa, localised',
      'Acute otitis media',
      'Pharyngitis',
      'Tonsillitis',
      'Chronic sinusitis',
      'Chronic suppurative otitis media',
      'Diphtheria',
      'Necrotising otitis externa',
      'Mastoiditis',
      'Peritonsillar abscess',
      'Retropharyngeal abscess',
      'Chronic otitis externa',
      'Invasive fungal sinusitis',
      'Laryngitis',
      'Gonococcal pharyngitis',
      'Otitis media with effusion',
      'Peritonsillar cellulitis',
      'Complicated acute rhinosinusitis',
      'Uncomplicated acute rhinosinusitis',
    ],
  },
  {
    group: 'eye',
    children: [
      'Blepharitis',
      'Bacterial conjunctivitis',
      'Bacterial keratitis',
      'Corneal abrasion',
      'Retinitis, other pathogen',
      'Cytomegalovirus retinitis',
      'Dacryocystitis',
      'Endophthalmitis',
      'Epiphora',
      'Herpes (varicella) zoster virus keratitis',
      'Herpes simplex virus keratitis',
      'Keratitis, other pathogen',
      'Meibomian abscess / chalazion',
      'Orbital cellulitis',
      'Periorbital cellulitis',
      'Stye',
      'Trachoma (chronic Chlamydial conjunctivitis)',
      'Acute Chlamydial conjunctivitis',
      'Viral conjunctivitis',
      'Retinitis, herpes simplex virus',
      'Herpes (varicella) zoster retinitis',
      'Penetrating eye injury',
      'Toxoplasma retinitis',
      'Uveitis',
    ],
  },
  {
    group: 'Gastrointestinal',
    children: [
      'Acute infectious diarrhoea',
      'Beef tapeworm (Taenia saginata)',
      'Blastocystis hominis',
      'Balantidium coli',
      'Enteritis: Campylobacter',
      'Cholera',
      'Clostridioides difficile infection',
      'Clostridioides difficile infection, recurrent',
      'Gastroenteritis: Cyclospora cayetanensis',
      'Cytomegalovirus colitis',
      'Cytomegalovirus oesophagitis',
      'Dientamoeba fragilis',
      'Dog hookworm (Ancylostoma caninum)',
      'Dwarf tapeworm (Hymenolepis nana)',
      'Entamoeba histolytica colitis / dysentery',
      'Entamoeba histolytica asymptomatic carriage',
      'Colitis',
      'Neutropenic enterocolitis',
      'Necrotising enterocolitis',
      'Enteritis: Escherichia coli',
      'Giardiasis',
      'Helicobacter pylori',
      'Herpes simplex virus oesophagitis',
      'Hookworm (Ancylostoma duodenale or Necator americanus)',
      'Gastroenteritis: Isospora belli',
      'Sarcosporidiosis',
      'Microsporidia infection',
      'Non cholera Vibrio enteritis',
      'Oesophageal candidiasis',
      'Deworming',
      "Perianal fistularising Crohn's disease",
      'Pilonidal sinus',
      'Pork tapeworm (Taenia solium), non neurological',
      'Roundworm (Ascaris lumbricoides)',
      'Enteritis: Salmonella',
      'Enteritis: Shigella',
      'Threadworm (Enterobius vermicularis)',
      'Travellers diarrhoea',
      'Whipworm (Trichuriasis)',
      'Enteritis: Yersinia',
      'Gastrointestinal decolonisation',
      'Gut dysmotility',
      'Hepatitis B',
      'Hepatitis C',
      'Hepatitis A',
      'Hepatitis E',
      'Hepatitis D',
      'Enteritis: Norovirus',
      'Enteritis: Rotavirus',
      'Enteritis: Adenovirus',
      'Enteritis: Enterovirus',
      'Enteritis: Astrovirus',
      'Enteritis: Aeromonas',
      'Perianal fistula',
      'Perianal / anorectal abscess',
      'Bunostomum phlebotomum',
      'Capillaria philippinensis',
      'Tracheoesophageal fistula',
      'Gastrointestinal / genitourinary fistula',
      'Inflammatory bowel disease',
      'Gastroenteritis: Cryptosporidium',
    ],
  },
  {
    group: 'Genital',
    children: [
      'Bacterial vaginosis',
      'Balanitis',
      'Mycoplasma genitalium',
      'Vulvovaginitis, other pathogen(s)',
      'Chancroid',
      'Donovanosis',
      'Epididymo-orchitis',
      'Herpes simplex virus anogenital',
      'Lymphogranuloma venereum',
      'Pelvic inflammatory disease',
      'Septic abortion',
      'Vulvovaginal candidiasis',
      'Syphilis, congenital',
      'Syphilis, early (primary or secondary)',
      'Syphilis, late, asymptomatic (latent)',
      'Neurosyphilis',
      'Syphilis, late, symptomatic (tertiary)',
      'Trichomoniasis',
      'Urethritis',
      'Cervicitis',
      'Anogenital warts',
      "Fournier's gangrene",
      'Gonorrhoea, other site or site not specified',
      'Chlamydia, other site or site not specified',
      'Pelvic abscess',
      'Chlamydia genitourinary infection',
      'Salpingitis',
      'Endometritis',
      'Chorioamnionitis',
      'Pelvic cellulitis',
      'Ureaplasma',
      'Cervicitis: Neisseria gonorrhoeae',
      'Epididymo-orchitis: Neisseria gonorrhoeae',
      'Pelvic inflammatory disease: Neisseria gonorrhoeae',
      'Urethritis: Neisseria gonorrhoeae',
      'Postprocedural pelvic infection',
      'Asymptomatic Neisseria gonorrhoeae',
      'Asymptomatic Chlamydia trachomatis',
      'Chlamydia trachomatis',
      'Neisseria gonorrhoeae',
    ],
  },
  {
    group: 'Intra-abdominal',
    children: [
      'Appendicitis',
      'Ascending cholangitis',
      'Diverticulitis',
      'Acute hepatic encephalopathy',
      'Amoebic liver abscess',
      'Liver Flukes',
      'Intestinal fluke',
      'Acute necrotising pancreatitis',
      'Peritonitis due to perforated viscus',
      'Prevention of recurrent cholangitis',
      'Spontaneous bacterial peritonitis',
      'Peritonitis complicating peritoneal dialysis',
      'Hydatid disease',
      'Acute pancreatitis (non-necrotising)',
      'Small intestinal bacterial overgrowth',
      'Proctitis',
      'Peritonitis, undifferentiated intra-abdominal source',
      'Acute acalculous cholecystitis',
      'Acute calculous cholecystitis',
      'Infective proctitis: Neisseria gonorrhoeae',
      'Pancreatic cyst / pseudocyst',
      'Intra-abdominal abscess - liver',
      'Intra-abdominal abscess - other (not liver)',
    ],
  },
  {
    group: 'Oral and Dental',
    children: [
      'Tooth avulsion',
      'Angular cheilitis',
      'Dental infection not otherwise specified',
      'Oral candidiasis',
      'Aphthous ulcers',
      'Gingivitis',
      'Periodontal abscess',
      "Ludwig's angina",
      'Salivary (parotid) gland infection',
      'Acute ulcerative gingivitis',
      'Periodontitis',
      'Dental caries',
    ],
  },
  {
    group: 'Other',
    children: [
      'Graft versus host disease',
      'Cushing syndrome',
      'Unknown (no documentation)',
      'Other',
    ],
  },
  {
    group: 'Prophylaxis - medical',
    children: [
      'Haemophilus influenzae type b clearance from index case',
      'Cytomegalovirus prophylaxis',
      'Herpes virus prophylaxis (HSV, VZV)',
      'Influenza prophylaxis',
      'Malaria prophylaxis',
      'Melioidosis prophylaxis',
      'Fungal infection prophylaxis',
      'Mycobacterium avium complex prophylaxis',
      'Pertussis prophylaxis',
      'Pneumocystis jirovecii pneumonia prophylaxis',
      'Post exposure prophylaxis for bloodborne viruses',
      'Post exposure prophylaxis for sexually transmitted infections',
      'Prophylaxis for endocarditis for dental procedure',
      'Prophylaxis for endocarditis for gastrointestinal procedure',
      'Prophylaxis for endocarditis for invasive ENT procedures',
      'Prophylaxis for endocarditis for genitourinary procedure',
      'Prophylaxis for endocarditis for respiratory tract procedure',
      'Prevention of infection in asplenic or hyposplenic hosts',
      'Prevention of infection in patients with cirrhosis and gastrointestinal bleeding',
      'Perinatal Group B Streptococcal prophylaxis',
      'Prevention of recurrent rheumatic fever',
      'Prevention of spontaneous bacterial peritonitis',
      "Prevention of traveller's diarrhoea",
      'Streptococcus pneumoniae prophylaxis',
      'Prophylaxis of Hepatitis B reactivation',
      'Toxoplasmosis prophylaxis',
      'Strongyloides prophylaxis',
      'Pre exposure prophylaxis for human immunodeficiency virus',
      'Prevention of hepatic encephalopathy',
      'Staphylococcus aureus decolonisation',
      'Prophylaxis for preterm prelabour rupture of membranes',
      'Prophylaxis, leech therapy',
      'Urinary tract infection prophylaxis',
      'Prophylaxis for potential organ donor',
      'Bacterial prophylaxis following lung transplant',
      'Medical prophylaxis; other',
      'Febrile neutropenia / neutropenic fever prophylaxis',
      'Prophylaxis for peritoneal dialysis catheter exit site infection',
      'Prophylaxis for endocarditis for infected skin, soft tissue surgery',
      'Group A Streptococcal prophylaxis',
      'Neisseria meningitidis post exposure prophylaxis',
      'Neisseria meningitidis clearance from index case',
      'Neisseria meningitidis prophylaxis (long term)',
      'Haemophilus influenzae type b post exposure prophylaxis',
    ],
  },
  {
    group: 'Prophylaxis - surgical',
    children: [
      'Surgical prophylaxis, abdominal / gastrointestinal procedure',
      'Surgical prophylaxis, breast procedure',
      'Surgical prophylaxis, cardiac procedure',
      'Surgical prophylaxis, dental / maxillofacial procedure',
      'Surgical prophylaxis, skin and soft tissue / dermatological procedure',
      'Surgical prophylaxis, head and neck / ear nose throat procedure',
      'Surgical prophylaxis, gynaecological procedure',
      'Surgical prophylaxis, neurosurgery',
      'Surgical prophylaxis, ophthalmic procedure',
      'Surgical prophylaxis, thoracic procedure',
      'Surgical prophylaxis, burns surgery',
      'Surgical prophylaxis, obstetric procedure',
      'Surgical prophylaxis, orthopaedic procedure',
      'Surgical prophylaxis, plastic surgery',
      'Prophylaxis, central nervous system device e.g. EVD, ICP, shunt',
      'Surgical prophylaxis, urological procedure',
      'Surgical prophylaxis, vascular procedure',
      'Surgical prophylaxis; other procedure(s)',
      'Prevention of infection post nasal packing for epistaxis',
      'Prophylaxis for cerebrospinal fluid leak',
      'Surgical prophylaxis, Procedure related to reproduction',
    ],
  },
  {
    group: 'Respiratory',
    children: [
      'Respiratory syncytial virus pneumonitis',
      'Respiratory syncytial virus bronchiolitis',
      'Rhinovirus',
      'Invasive pulmonary aspergillosis',
      'Bronchiolitis',
      'Allergic bronchopulmonary aspergillosis',
      'Pulmonary Cryptococcosis',
      'Pneumonia, aspiration, community acquired',
      'Pneumonia, aspiration, hospital acquired',
      'Bronchiectasis, acute exacerbation',
      'Chronic obstructive pulmonary disease (COPD), acute exacerbation',
      'Croup',
      'Cystic fibrosis, long term management',
      'Cystic fibrosis, acute exacerbation',
      'Influenza (without pneumonia)',
      'Lung abscess',
      'Mediastinitis',
      'Parapneumonic effusion',
      'Empyema',
      'Pneumonia: Streptococcus pneumoniae',
      'Pneumonia: Staphylococcus aureus',
      'Pneumonia: Haemophilus influenzae',
      'Pneumonia: Legionella species',
      'Pneumonia: Mycoplasma species',
      'Pneumonia: Pseudomonas species',
      'Pneumonia: Burkholderia pseudomallei (melioid)',
      'Pneumonia: Chlamydophila psittaci',
      'Pneumonia: Chlamydophila pneumoniae',
      'Pneumonia: Coxiella burnetii',
      'Pneumonia; other pathogen(s)',
      'Pneumocystis jirovecii pneumonia',
      'Pneumonia, aspiration, post near drowning',
      'Pneumonia, community acquired, pathogen unknown',
      'Pneumonia, community acquired, tropical Australia, pathogen unknown',
      'Pneumonia, hospital acquired, pathogen unknown',
      'Pneumonia, ventilator associated, pathogen unknown',
      'Influenza pneumonitis (pneumonia)',
      'Viral respiratory infection, other pathogen(s)',
      'Asthma, infective exacerbation',
      'Bronchiectasis, long term management',
      'Bronchiolitis obliterans',
      'Bronchitis',
      'Chronic obstructive pulmonary disease (COPD), long term management',
      'Nocardia, pulmonary infection',
      'Tuberculosis, pulmonary',
      'Severe acute respiratory syndrome (SARS coronavirus)',
      'Middle East respiratory syndrome (MERS coronavirus)',
      'Mycobacterium avium complex, pulmonary infection',
      'Pertussis',
      'Nontuberculous mycobacterial pulmonary infection',
      'Upper respiratory tract infection, not otherwise specified',
      'Pneumonia: Acinetobacter baumannii',
      'Pneumonia: Enterobacter species',
      'Pneumonia: Klebsiella pneumoniae',
      'Pneumonitis: Cytomegalovirus',
      'Pneumonia: Stenotrophomonas maltophilia',
      'Bronchiectasis, eradication therapy',
      'Acute exacerbation of interstitial lung disease',
      'Pneumonia, community acquired, aged care home resident',
      'Pneumonia, aspiration, community acquired, aged care home resident',
      'COVID-19 (SARS-CoV-2)',
      'Chronic pulmonary aspergillosis',
      'Aspergilloma',
      'Invasive pulmonary fungal infection, other',
      'Chemical aspiration pneumonitis (excluding aspiration pneumonia)',
    ],
  },
  {
    group: 'Sepsis and bacteraemia',
    children: [
      'Fungaemia, yeast',
      'Fungaemia, other (non yeast)',
      'Febrile neutropenia / neutropenic fever',
      'Bacteraemia; other pathogen(s)',
      'Bacteraemia: Staphylococcus aureus',
      'Bacteraemia: Pseudomonas aeruginosa',
      'Bacteraemia: Escherichia coli',
      'Bacteraemia: Neisseria meningitidis',
      'Bacteraemia: Klebsiella pneumoniae',
      'Bacteraemia: Enterococcus species',
      'Bacteraemia: Streptococcus species',
      'Bacteraemia: Enterobacter species',
      'Bacteraemia: Staphylococcus species, other (not aureus)',
      'Bacteraemia, Gram positive bacteria, pending identification',
      'Bacteraemia, Gram negative bacteria, pending identification',
      'Sepsis, unknown source, community acquired',
      'Sepsis, intravascular access device source',
      'Toxic shock syndrome, Staphylococcal',
      'Toxic shock syndrome, Streptococcal',
      'Typhoid and paratyphoid fever',
      'Early-onset neonatal sepsis',
      'Late-onset neonatal sepsis',
      'Sepsis, unknown source, healthcare associated',
      'Sepsis, unknown source, community acquired, tropical region',
    ],
  },
  {
    group: 'Skin and Soft Tissue',
    children: [
      'Seborrhoeic dermatitis',
      'Erythrasma',
      "Sweet's syndrome",
      'Acne',
      'Acute paronychia',
      'Wound infection, water related',
      'Skin and soft tissue infection, other',
      'Bite or clenched fist injury (human)',
      'Animal bite wound',
      'Body lice',
      'Boils or carbuncles',
      'Cellulitis',
      'Erysipelas',
      'Prevention of recurrent cellulitis',
      'Cervical lymphadenitis, suppurative',
      'Crusted (Norwegian) scabies',
      'Cutaneous candidiasis',
      'Cutaneous larvae migrans (animal hookworm)',
      'Diabetic foot infection',
      'Folliculitis',
      'Head lice',
      'Herpes simplex virus, oral mucocutaneous (including labialis and gingivostomatitis)',
      'Herpetic whitlow',
      'Impetigo',
      'Intramuscular abscess (including psoas)',
      'Infected breast prosthesis',
      'Infected hernia mesh',
      'Necrotising fasciitis',
      'Pityriasis versicolor',
      'Post-traumatic wound infection',
      'Pubic lice',
      'Recurrent boils, Staphylococcus aureus',
      'Perioral dermatitis',
      'Bromhidrosis',
      'Pitted keratolysis',
      'Neonatal cephalic pustulosis',
      'Infantile acne',
      'Nappy rash',
      'Rosacea',
      'Scabies',
      'Tinea, other',
      'Onychomycosis',
      'Pruritis, cholestatic liver disease',
      'Dermatitis herpetiformis',
      'Bullous pemphigoid',
      'Dermatitis',
      'Wound infection, surgical site',
      'Hidradenitis suppurativa',
      "Grover's disease",
      'Burns related wound infection',
      'Varicella zoster virus disseminated (multidermatomal shingles)',
      'Varicella (herpes) zoster virus - shingles',
      'Eczema herpeticum',
      'Septic thrombophlebitis',
      'Cellulitis related to intravascular access device, local inflammation',
      'Infected skin ulcer',
      'Mycetoma',
      'Pressure ulcer',
      'Mycobacterium ulcerans (Buruli ulcer)',
      'Skin tear',
      'Skin and soft tissue abscess',
      'Staphylococcal scalded skin syndrome',
      'Erythema nodosum',
      'Varicella zoster virus - chickenpox',
      'Coxsackievirus',
      'Molluscum contagiosum',
      'Dracunculus medinensis',
      'Nontuberculous mycobacterial skin / soft tissue infection',
      'Infected eczema',
      'Insect or spider bite',
      'Burn, pre-emptive therapy',
      'Infected sebaceous cyst',
      'Mastitis',
      'Breast abscess',
      'Prophylaxis for post-traumatic wound',
      'Onycholysis',
      'Septic jugular thrombophlebitis (Lemierre Syndrome)',
      'Nocardia, cutaneous',
      'Nipple candidiasis',
      'Pruritus ani',
      'Tinea capitis',
    ],
  },
  {
    group: 'Systemic infections',
    children: [
      'Strongyloidiasis',
      'Bartonella henselae infection (cat scratch)',
      'Brucellosis',
      'Cytomegalovirus systemic infection',
      'Dengue',
      "Bell's palsy (incl. Ramsay Hunt syndrome)",
      'Filariasis',
      'Herpes simplex virus in neonates',
      'Human immunodeficiency virus infection',
      'Latent tuberculosis',
      'Leptospirosis',
      'Melioidosis',
      'Mycobacterium avium complex, disseminated',
      'Nontuberculous mycobacterial infection, systemic / disseminated / other',
      'Pinta',
      'Q fever (Coxiella burnetii), systemic illness - acute',
      'Q fever (Coxiella burnetii), systemic illness - chronic',
      'Rickettsial infection',
      'Rheumatic fever',
      'Schistosomiasis',
      'Invasive aspergillosis (non-pulmonary)',
      'Smallpox',
      'BK virus',
      'Progressive multifocal leucoencephalopathy (JC virus)',
      'Disseminated tuberculosis',
      'Tuberculosis, extrapulmonary (non-meningitis)',
      'Tularaemia',
      'Varicella zoster virus, neonatal',
      'Glanders',
      'Granulomatosis with polyangiitis',
      'Anthrax',
      'Bartonella infection, non-henselae',
      'Botulism',
      'Cytomegalovirus in neonates / congenital',
      'Herpes simplex virus disseminated',
      'Leishmaniasis',
      'Leprosy',
      'Lyme disease',
      'Mycobacterium avium complex, cervical lymphadenitis',
      'Psittacosis, systemic illness',
      'Rabies prophylaxis, post exposure',
      'Australian bat lyssavirus',
      'Tetanus',
      'Legionella, systemic illness (Pontiac fever)',
      'Zika virus',
      'Chikungunya',
      'Ross river fever',
      'Yellow fever',
      'Viral haemorrhagic fever',
      'Fever of unknown origin',
      'Toxoplasmosis, systemic (non central nervous system)',
      'Congenital toxoplasmosis',
      'Epstein-Barr virus',
      'Polio',
      'Measles',
      'Mumps',
      'Rubella',
      'Yaws',
      'Barmah forest disease',
      "Whipple's disease",
      'Zygomycosis (including Mucormycosis)',
      'Fusariosis',
      'Fungal infection, Scedosporium',
      'Sporotrichosis',
      'Histoplasmosis',
      'Blastomycosis',
      'Coccidioidomycosis',
      'Plague (Yersinia pestis)',
      'Invasive fungal infection, other pathogen',
      'Adenovirus (non-gastrointestinal)',
      'Parechovirus',
      'Scarlet fever (Streptococcus pyogenes)',
      'Babesia',
      'Toxocara',
      'Mansonella',
      'Post transplant lymphoproliferative disorder',
      'Trichinella',
      'Diphyllobothrium latum',
      'Paragonimiasis',
      'Human herpes virus 6',
      'Human herpes virus 8',
      'Infection of prosthetic device not otherwise specified',
      'Disseminated yeast infection (including hepatosplenic)',
      'Actinomycosis infection',
      'Cryptococcosis, disseminated / other',
      'Debilitating symptom complexes attributed to ticks',
      'Systemic illness of unknown origin',
      'Disseminated infection: Neisseria gonorrhoeae',
      'Malaria: Plasmodium falciparum',
      'Malaria: Plasmodium vivax',
      'Malaria: Plasmodium ovale',
      'Malaria: other',
      'Nocardia, disseminated',
      'Nocardia, other',
      'Fungal infection, Lomentospora',
    ],
  },
  {
    group: 'Urinary tract',
    children: [
      'Acute cystitis, pathogen unknown',
      'Acute cystitis: Escherichia coli',
      'Acute cystitis: Enterococcus species',
      'Acute cystitis: Proteus mirabilis',
      'Acute cystitis: Klebsiella pneumoniae',
      'Acute cystitis: Pseudomonas aeruginosa',
      'Acute cystitis; other pathogen(s)',
      'Acute prostatitis',
      'Acute pyelonephritis / urosepsis, pathogen unknown',
      'Acute pyelonephritis / urosepsis: Escherichia coli',
      'Acute pyelonephritis / urosepsis: Enterococcus species',
      'Acute pyelonephritis / urosepsis: Proteus mirabilis',
      'Acute pyelonephritis / urosepsis: Klebsiella pneumoniae',
      'Acute pyelonephritis / urosepsis: Pseudomonas aeruginosa',
      'Acute pyelonephritis / urosepsis; other pathogen(s)',
      'Asymptomatic bacteriuria',
      'Candiduria',
      'Chronic bacterial prostatitis',
      'Catheter associated urinary tract infection',
      'Manipulation of urinary catheter',
      'Prostate abscess',
      'Renal abscess',
      'Urinary stent-associated bacteriuria',
    ],
  },
];
