  - name: Stop and remove the existing '{{di_auth_image_name}}' Docker container
    docker_container:
      name: '{{di_auth_image_name}}'
      image: '{{di_auth_image_name}}'
      state: absent

  - name: Remove the '{{di_auth_image_name}}' Docker image
    docker_image:
      name: '{{di_auth_image_name}}'
      state: absent

  - name: Create docker '{{di_auth_image_name}}' docker image
    docker_image:
      name: '{{di_auth_image_name}}'
      source: build
      state: present
      build: 
        path: '{{local_work_dir}}/{{di_auth_module_name}}'
        nocache: yes
      
  - name: Run the '{{di_auth_image_name}}' Docker image
    docker_container:
      name: '{{di_auth_image_name}}'
      image: '{{di_auth_image_name}}'
      state: started
      networks:   # Join the same docker network
        - name: '{{docker_network_name}}'
      published_ports:
        - '{{di_auth_host_port}}:{{di_auth_container_port}}' 
      # env:
      #     DB_USERNAME: '{{mongo_db_user}}'
      #     DB_PASSWORD: '{{mongo_db_password}}'
      #     DB_HOST: '{{mongo_db_host}}'
      #     DB_HOST_PORT: '{{mongo_db_host_port}}'