docker_network_name: di
# local_work_dir: ../src/
# remote_work_dir: ./DI-Boxjelly/src  # Move the 'src' folder into the remote ./DI-Boxjelly

# nginx setting
nginx_name: nginx
nginx_module_name: di-nginx
nginx_config_name: nginx.conf
nginx_host_port: 80
nginx_container_port: 80

# mongodb setting
mongo_db_name: mongo

# di_gateway
di_gateway_module_name: di-gateway
di_gateway_image_name: di_gateway
di_gateway_container_name: di_gateway
di_gateway_container_port: 8080
di_gateway_host_port: 8080

# di_auth
di_auth_module_name: di-auth
di_auth_image_name: di_auth
di_auth_container_name: di_auth
di_auth_container_port: 8001
di_auth_host_port: 8001

# di_web
di_web_module_name: di-web
di_web_image_name: di_web
di_web_container_name: di_web
di_web_container_port: 8000
di_web_host_port: 8000