docker_network_name: di

# nginx setting
nginx_name: nginx
nginx_config_name: nginx.conf
nginx_host_port: 80
nginx_container_port: 80
nginx_local_work_dir: ../src/di-nginx
nginx_remote_work_dir: ./DI-Boxjelly/src/nginx

# mongodb setting
mongo_db_name: mongo

# di_gateway
di_gateway_module_name: di-gateway
di_gateway_image_name: di_gateway
di_gateway_local_work_dir: ../src/di-gateway
di_gateway_remote_work_dir: ./DI-Boxjelly/src/
di_gateway_container_name: di_gateway
di_gateway_container_port: 8080
di_gateway_host_port: 8080

# di_auth
di_auth_module_name: di-auth
di_auth_image_name: di_auth
di_auth_local_work_dir: ../src/di-auth
di_auth_remote_work_dir: ./DI-Boxjelly/src/
di_auth_container_name: di_auth
di_auth_container_port: 8001
di_auth_host_port: 8001
