  - name: Pull the mongodb latest image
    community.docker.docker_image:
      name: mongo
      tag: latest
      source: pull
      # Select platform for pulling. If not specified, will pull whatever docker prefers.
      pull:
        platform: amd64

  - name: Deploy the mongodb container
    docker_container:
      image: mongo
      name: '{{mongo_db_name}}'
      ports: 
        - '{{mongo_db_host_port}}:{{mongo_db_container_port}}'
      restart: yes  # if restart is yes, it will not remove the previous container
      env:
          MONGO_INITDB_ROOT_USERNAME: '{{mongo_db_user}}'
          MONGO_INITDB_ROOT_PASSWORD: '{{mongo_db_password}}'
      state: started
      networks: 
        - name: '{{docker_network_name}}'
