  - name: Pull the nginx latest image
    community.docker.docker_image:
      name: nginx
      tag: latest
      source: pull
      # Select platform for pulling. If not specified, will pull whatever docker prefers.
      pull:
        platform: amd64

  # transfer the target module to the remote instance
  # - name: Synchronize '{{di_gateway_module_name}}' module code with remote server
  #   ansible.builtin.synchronize:
  #     src: '{{nginx_local_work_dir}}'
  #     dest: '{{nginx_remote_work_dir}}'
  #     delete: yes
  #     recursive: yes
  #     rsync_opts:
  #       - "--exclude=.git"
  #       - "--exclude-from=../.gitignore"
  # - name: Copy custom nginx.conf file to the remote server
  #   ansible.builtin.copy:
  #     src: '{{nginx_local_work_dir}}'
  #     dest: '{{nginx_remote_work_dir}}'
  #     mode: '0644'

  - name: Stop and remove the existing '{{nginx_name}}' Docker container
    docker_container:
      name: nginx
      image: '{{nginx_name}}'
      state: absent

  - name: Deploy the nginx container
    docker_container:
      image: nginx
      name: '{{nginx_name}}'
      ports: 
        - '{{nginx_host_port}}:{{nginx_container_port}}'
      restart: yes  # if restart is yes, it will not remove the previous container
      state: started
      networks: 
        - name: '{{docker_network_name}}'
      volumes:
        - '{{nginx_conf_path}}:/etc/nginx/conf.d/default.conf'
        # - "/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"

        # - '{{nginx_remote_work_dir}}:/etc/nginx/conf.d/default.conf'
