  - name: Pull the nginx latest image
    community.docker.docker_image:
      name: nginx
      tag: latest
      source: pull
      # Select platform for pulling. If not specified, will pull whatever docker prefers.
      pull:
        platform: amd64

  # Create nginx directory on the remote server
  # - name: Create custom_nginx_config directory on the remote server
  #   ansible.builtin.file:
  #     path: '{{remote_work_dir}}/{{nginx_module_name}}'
  #     state: directory
  #     mode: '0755'

  # - name: Copy custom nginx.conf file to the remote server
  #   ansible.builtin.copy:
  #     src: '{{local_work_dir}}/{{nginx_module_name}}/{{nginx_config_name}}'
  #     dest: '{{remote_work_dir}}/{{nginx_module_name}}/{{nginx_config_name}}'
  #     mode: '0644'

  - name: Stop and remove the existing '{{nginx_name}}' Docker container
    docker_container:
      name: nginx
      image: '{{nginx_name}}'
      state: absent

  - name: Deploy the nginx container
    docker_container:
      image: nginx
      name: '{{nginx_name}}'
      ports: 
        - '{{nginx_host_port}}:{{nginx_container_port}}'
      restart: yes  # if restart is yes, it will not remove the previous container
      state: started
      networks: 
        - name: '{{docker_network_name}}'
      volumes:
        - '{{work_dir}}/{{nginx_module_name}}/{{nginx_config_name}}:/etc/nginx/conf.d/default.conf'
        # - "/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"

        # - '{{nginx_remote_work_dir}}:/etc/nginx/conf.d/default.conf'
