  - name: Stop and remove the existing '{{nginx_image_name}}' Docker container
    docker_container:
      name: '{{nginx_image_name}}'
      image: '{{nginx_image_name}}'
      state: absent

  - name: Remove the '{{nginx_image_name}}' Docker image
    docker_image:
      name: '{{nginx_image_name}}'
      state: absent

  - name: Create docker '{{nginx_image_name}}' docker image
    docker_image:
      name: '{{nginx_image_name}}'
      source: build
      state: present
      build: 
        # we use the Dockerfile in di-web to build nginx
        # Add the static file into the nginx port 80,
        # and add the gateway to the nginx port 8000
        path: '{{work_dir}}/{{di_web_module_name}}' 
        nocache: yes
      
  - name: Run the '{{nginx_image_name}}' Docker image
    docker_container:
      name: '{{nginx_image_name}}'
      image: '{{nginx_image_name}}'
      state: started
      networks:   # Join the same docker network
        - name: '{{docker_network_name}}'
      published_ports:
        - '{{di_web_host_port}}:{{di_web_container_port}}'  # 80:80
        - '{{di_gateway_host_port}}:{{di_gateway_container_port}}'  #8000:8000

     
