# - hosts: all
#   become: true
#   vars_files:
#       - vars/dev-common.yaml
#   roles:
#     - role: linux-install-docker
    
# - hosts: mongodb
#   become: true
#   vars_files:
#     - vars/dev-common.yaml
#   roles:
#     - role: linux-deploy-mongodb

- hosts: di_gateway
  become: true
  vars_files:
    - vars/dev-common.yaml
  roles:
    - role: linux-deploy-di-gateway
