# Deploy the DI project locally
- name: Deploy the DI-Boxjelly project
  hosts: local
  become: true
  vars:
    - work_dir: ../src
  vars_files: 
    - vars/settings.yml
  pre_tasks:
    - name: Install docker installer
      command: ansible-galaxy install geerlingguy.docker
    - name: Install docker locally
      include_role: 
        name: geerlingguy.docker
    - name: Create docker network
      docker_network:
        name: '{{docker_network_name}}'
    - name: Pull python flask image
      command: docker pull python:3.9.16-slim-bullseye

  roles:
    - nginx          # Deploy the web
    - di-gateway      # Deploy the gateway  service
    - mongodb         # Deploy MongoDB
    - di-auth         # Deploy the authentication service
