  - name: Stop and remove the existing '{{di_gateway_image_name}}' Docker container
    docker_container:
      name: '{{di_gateway_image_name}}'
      image: '{{di_gateway_image_name}}'
      state: absent

  - name: Remove the '{{di_gateway_image_name}}' Docker image
    docker_image:
      name: '{{di_gateway_image_name}}'
      state: absent

  - name: Create docker '{{di_gateway_image_name}}' docker image
    docker_image:
      name: '{{di_gateway_image_name}}'
      source: build
      state: present
      build: 
        path: '{{work_dir}}/{{di_gateway_module_name}}'
        nocache: yes
      
  - name: Run the '{{di_gateway_image_name}}' Docker image
    docker_container:
      name: '{{di_gateway_container_name}}'
      image: '{{di_gateway_image_name}}'
      state: started
      networks:   # Join the same docker network
        - name: '{{docker_network_name}}'
